version: '3'
services:
  interpreter:
    build: .
    ports:
      - "8501:8501"  # Streamlit
      - "5900:5900"  # VNC
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./:/app
    restart: unless-stopped
